language: node_js
node_js:
- 10.15.0
cache: npm
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJHYPE3NW6GHJF3SA
  secret_access_key:
    secure: "Jbxn0FAcR6Z84hmdilsD2bIzuAqaNyYuIPHPA7Vye15jFvMO8IG9QyxEfvyVgNlFxeNrnrE2uI5pISR9GXrMyyiwBQgMUCoGNv2RI7VcyZ2FjXVJAtVrH9PFvI7t6lbAQmQicXrICqCBR3peu8exV7wHclKf6DOEGWTMofRiLA2oPoMH3/Q/2T4iWQrJK/mZ/lqBfZXCFITbi0Mz+w46uL098Hqozgq2JaQnOnq9EyYsZBJKqSrvVRe+MgN01m1WBgkZLnPNBywGsJtds7HjBOBhIWHS0XaHOQARPvKnBbLs5Y24eesIJ+X0CauGQpO5r4qjOPyhKpUrE6Y0uwsi1gijQs2Rec8OeHrYDg3qdrAD0zLknveQ/1xCoO45v7GPy5BC2Zeq8UkjRY9vmN0papBdbmPQaC9I2JydilqkeUDYBOgYeEReqE7SSD+64CJSXp5oTmpBIcMxIqd8YWm+fF2sFQ53YPqUhGljTmYo25CR/xGyULJuw+xhH+xf0oCr1DGoJkeMcHkVlYEmh2exRTsTIIJI9V0wxJaXiZWOa46BbdRo75mSPya3kFwDFG8x2raxap7/rn1txcxQYRjcLicQekvUagF65qTljMjd4MkXrRca6mI7ERsBS3XoPE5LMN/JFVgPSmyHz9Zad8uJMbVTTWoanG66ae9zOR+7JNg="
  region: eu-west-2
  app: pizza-luvrs
  env: pizza-luvrs-dev-v2
  bucket_name: elasticbeanstalk-eu-west-2-867100921759
  bucket_path: pizza-luvrs
  on:
    repo: dikaeinstein/pizza-luvrs
    branch: master
